# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
dist: xenial

services:
  - xvfb

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - devtools
r_github_packages: r4ss/r4ss@development

warnings_are_errors: false
