# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
dist: xenial

services:
  - xvfb

notifications:
  email:
    recipients:
      - kelli.johnson@noaa.gov
      - kathryn.doering@noaa.gov
    on_success: change
    on_failure: always

r_packages:
  - devtools

warnings_are_errors: false
