language: r
sudo: required
cache: packages
r: devel

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 4 # give xvfb some time to start

notifications:
  email:
    on_success: change
    on_failure: change

warnings_are_errors: false

# r_github_packages:
#  - r4ss/r4ss
